# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

blackW/black_locked_wheels:
  model_name: "best.pt"
  force_policy_transition: true
  policy_transition_cycles: 2000
  enter_getup_after_transition: true
  num_observations: 45
  observations: ["commands","ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
  observations_history: [0,1,2,3,4,5]  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0]
  rl_kp: [50.0, 50.0, 50.0, 80.0,
          50.0, 50.0, 50.0, 80.0,
          50.0, 50.0, 50.0, 80.0,
          50.0, 50.0, 50.0, 80.0]
  rl_kd: [1.2, 1.2, 1.2, 3.0,
          1.2, 1.2, 1.2, 3.0,
          1.2, 1.2, 1.2, 3.0,
          1.2, 1.2, 1.2, 3.0]
  fixed_kp: [80.0, 80.0, 80.0, 80.0,
             80.0, 80.0, 80.0, 80.0,
             80.0, 80.0, 80.0, 80.0,
             80.0, 80.0, 80.0, 80.0]
  fixed_kd: [3.0, 3.0, 3.0, 3.0,
             3.0, 3.0, 3.0, 3.0,
             3.0, 3.0, 3.0, 3.0,
             3.0, 3.0, 3.0, 3.0]
  num_of_dofs: 16
  policy_dof_indices: [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14]
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]
  wheel_indices: [3, 7, 11, 15]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [33.5, 33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5, 33.5,
                  33.5, 33.5, 33.5, 33.5]
  default_dof_pos: [0.0, 0.8014, -1.527, 0.0,
                    -0.0, -0.8014, 1.527, 0.0,
                    -0.0, 0.8014, -1.527, 0.0,
                    0.0, -0.8014, 1.527, 0.0]
  joint_mapping: [4, 5, 6, 7, 0, 1, 2, 3, 12, 13, 14, 15, 8, 9, 10, 11]
